version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aspor-extraction-platform"
s3_bucket = "aws-sam-cli-managed-default-samcliamebucket"
s3_prefix = "aspor-extraction-platform"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BedrockModelId=\"anthropic.claude-3-opus-20240229\""